### PR TITLE
Added rough template for application documentation, and draft example for vasp

### PR DESCRIPTION
**Pull request by james-grant1**
Includes readme for template, new template fodler with application.rst but not referenced dummy files.
vasp.rst includes documentation items as per Archer's packages and linked files in local folder applications/vasp and for website, _static/applications/vasp.
This isn't pretty but might be resolved by creating another repository for builds, as Archer now do?

### CODE REVIEW

**Comment by jrprice** [comment]
Looks good in general, thanks for getting this done.

When building this, I get lots of warnings of the form:
```/Users/james/projects/isambard/docs/applications/vasp.rst:5: WARNING: Title underline too short.```
I think you just need to extend the `----` underlines to match the length of the title. I appreciate that the VASP page is still a draft, but we should at least fix this in the template so that it doesn't propagate to other apps.

I'm not keen on the idea of duplicating the extra files (e.g. Makefiles) - they'd be prone to getting out of sync if someone forgot to copy them over to `_static_`. Sphinx provides a `:download:` directive which can be used to link to additional downloadable content, which doesn't require manually putting a copy in `_static`.

**Comment by james-grant1** [comment]
Changed template and vasp example to remove warnings.  As JP noted heading identifiers need to be at least length of the heading otherwise warning flags.  vi accepts anything greater than length 2, to confuse the issue and there appears to be no way to suppress the warning.

Incorporated download to simplify linking to files!  Also improved(!?) the template so that build instructions are displayed rather than a separate link.  And duplicated to the template application along with dependant files.

Issues:: 

- Removal of _static/<files> causes warning on build but is present in master.
- Templates not included in build results in warning, probably just include 'templates' in 'excluded_patterns' in conf.py, but we may want to be more specific and reference actual files and subdirectories? 
- On local build applications listings in sidebar only show on index page, except when vasp is followed.  Can't see what might be causing this.

**Comment by jrprice** [comment]
Looks good, I like the way the VASP page looks now.

Not worried about the warning about missing `_static` - this will go away when we add some files (images for GW4/EPSRC/MO logos for example).

I think excluding the whole templates directory is fine, I can't imagine we will want to use that directory for pages that we actually want to build.

Can't reproduce your issue with the sidebar on the VASP page, seems to be fine for me. Could be a local issue, so let's just check if it persists when this is merged and deployed.

**Comment by james-grant1** [comment]
Templates folder added to exclude_patterns in conf.py.  Should be good to merge.

**Comment by jrprice** [comment]
Merged, thanks for this.

**Pull request merged**
