### PR TITLE
Resolution of RT #724: Craype-accel-nvidia70 on volta

### PR DESCRIPTION
**Pull request by JBotwright**
Resolution of RT #724: Craype-accel-nvidia70 on volta
by adding a short paragraph to the MACS Volta section

### CODE REVIEW

**Comment by heaton-dev** [comment]
I think the docs should default to telling the user how to use the system-provided software/modules instead of suggesting they bring their own.  i.e. "if you're using a Nvidia GPU node then you must load `cuda10.2/...`"

Also I'm not sure the cudatoolkit module and cuda10.x/... modules serve the same purpose, so mentioning it here might confuse people

**Comment by JBotwright** [comment]
The cray software stack in /opt/cray/pe/craype/default/modulefiles is agnostic of the driver because it is provided by Bright.
My suggestion to swap the cudatoolkit/X.Y module (which the cray image loads when you log into the Voltas) with the Bright cuda/X.Y/toolkit will load the location of the driver into the library path. More info from Pete Leggett is in the RT issue and I believe Cray are working on making this easier for end users.

**Comment by heaton-dev** [comment]
It seems we need some clarification from Cray; my understanding was that cudatoolkit is a Cray module, since it's installed in `/global/opt` instead of the Bright location of `/cm`

Also when I start an interactive job on pascalq and voltaq I don't get any modules preloaded:

```
login-01:~> qsub -I -X -q pascalq
pascal-002:pbs.38634.master.gw4.metoffice.gov.uk.x8z> module list
Currently Loaded Modulefiles:
  1) craype-broadwell            2) craype-network-infiniband
```

```
login-01:~> qsub -I -X -q voltaq
volta-003:pbs.38635.master.gw4.metoffice.gov.uk.x8z> module list
Currently Loaded Modulefiles:
  1) craype-broadwell            2) craype-network-infiniband
```

**Comment by JBotwright** [comment]
Good spot! Looks like something is broken as the module appends /opt/cray/nvidia/default/bin to PATH but that folder no longer exists. I'll investigate further.

**Comment by JBotwright** [comment]
It looks to me like whoever authored the cray module started to try to make it link into the system but failed because in addition to the missing folder, it also tries to provide cuda and cudart via pkg-config but they do not work either. I won;t continue investigating why it does not work, I'll just accept that "module load craype-accel-nvidia-??; nvcc myprogram.cu" does not lead to an executable a.out.
That leaves the official workaround from Pete L at cray which is to provide knowledge of the driver location to nvcc, or Tom Deakin's suggestion which is to load a bright module from /cm/shared/modulefiles instead.

**Comment by heaton-dev** [comment]
Do you still want this merged as-is?

**Pull request closed without merging**
